
services:
  db:
    image: mariadb:11.3
    container_name: deckplanner_mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: deckplanner_backend
    command: sh -c "docker/entrypoint.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy